local o = vim.o
local go = vim.go
local bo = vim.bo
local wo = vim.wo

go.syntax = 'on'
bo.autoindent = true
go.background = 'dark'
go.clipboard = 'unnamedplus'
go.cmdheight = 2
wo.colorcolumn = '80'
wo.conceallevel = 0
wo.cursorline = true
bo.expandtab = true
--bo.formatoptions = 'cro'
go.hidden = true
go.incsearch = true
o.ignorecase = true
go.laststatus = 0
go.mouse = 'a'
go.errorbells = false
go.hlsearch = false
go.showmode = false
wo.wrap = false
wo.number = true
go.pumheight = 10
wo.relativenumber = true
go.ruler = true
go.scrolloff = 8
bo.shiftwidth = 4
go.showtabline = 2
wo.signcolumn = 'yes'
go.smartcase = true
bo.smartindent = true
go.splitbelow = true
go.splitright = true
bo.tabstop = 4
bo.softtabstop = 4
go.termguicolors = true
go.t_Co = '256'
go.updatetime = 300
