local o = vim.o
local go = vim.go

o.syntax = "on"
o.autoindent = true
o.background = "dark"
o.clipboard = "unnamedplus"
o.cmdheight = 2
o.colorcolumn = "80"
o.conceallevel = 0
o.cursorline = true
vim.opt.formatoptions:remove( { "c", "r", "o" } )
o.hidden = true
o.incsearch = true
o.ignorecase = true
o.laststatus = 0
o.mouse = "a"
o.errorbells = false
o.hlsearch = false
o.showmode = false
o.wrap = false
o.number = true
o.pumheight = 10
o.relativenumber = true
o.ruler = true
o.scrolloff = 8
o.shiftwidth = 4
o.showtabline = 2
o.signcolumn = "yes"
o.smartcase = true
o.smartindent = true
o.splitbelow = true
o.splitright = true
o.tabstop = 4
o.softtabstop = 4
o.termguicolors = true
go.t_Co = "256"
o.updatetime = 300
